### PR TITLE
Send all not currently handled event type to raw 8002 message

### PR DESCRIPTION
**Pull request by badzz**
Until now some events were not handled and thrown away, this patch changes the behaviour to have them sent as raw 8002 message. This will allow us to deal with read request for example from some devices

### CODE REVIEW

**Comment by fairecasoimeme** [comment]
Thx a lot !
I will test and see
Fred

**Comment by badzz** [comment]
It does not work as expected as the firmware keep sending its response
'unknown attribute'. I will change the PR and re submit once everything is
resolved
Thanks

**Comment by fairecasoimeme** [comment]
OK

**Comment by badzz** [comment]
Modifed to make it work.
It was still answering "unknown attribute" after calling the callback function
I had to free myPDUM_thAPduInstance to avoid memory leak

**Comment by fairecasoimeme** [comment]
OK,
But could you make changes with the 3.1d branch please ?
Fred

**Comment by badzz** [comment]
new PR created 
https://github.com/fairecasoimeme/ZiGate/pull/283

**Pull request closed without merging**
