### PR TITLE
add rawmode hybrid and keep existing one

### PR DESCRIPTION
**Pull request by badzz**

### CODE REVIEW

**Comment by fairecasoimeme** [comment]
Hello,
@doudz , could you tell us if the rawmode update in this PR is a problem for you or not ?
thx

**Comment by doudz** [comment]
No problem for me since the original rawmode is preserved.
But what's the purpose of this hybrid mode ?

**Comment by pipiche38** [comment]
> No problem for me since the original rawmode is preserved.
> But what's the purpose of this hybrid mode ?

The purpose is to get all messages when dealing with new/unknown/special devices ; as well as debuging purposes

**Comment by doudz** [comment]
ok thanks for the answer.
I'll see, maybe it could be use as replacement of the current raw mode

**Comment by fairecasoimeme** [comment]
It's ok

**Pull request merged**
