### PR TITLE
Initial version of WindowCovering cluster

### PR DESCRIPTION
**Pull request by ISO-B**
Includes only client functions of cluster since ZiGate is not designed to work as window covering controller

### CODE REVIEW

**Comment by fairecasoimeme** [comment]
works fine

**Comment by pipiche38** [comment]
@ISO-B I have a question related  to LIFT % with command '05'. Is 0% and 100% allow ?
Do we agree that 0% is equivalent to Close and 100% is equivalent to Open

**Comment by pipiche38** [comment]
IS anyone tested the STOP fonction yet ?

**Comment by ISO-B** [comment]
I didn't test any functions since I don't have blinds. I think 0% and 100% should be allowed unless end device has other limits set. Blinds device should have config attributes(0x0007) for window covering cluster which has parameter for that tells if 0% or 100% is close.

More info can be found from ZigBee Document – 075123 Chapter 7.4.2.1.1

**Pull request merged**
