### PR TITLE
Incremented pointer reference when reading data other than uint8 from reports.

### PR DESCRIPTION
**Pull request by schrodingersket**
#223

### CODE REVIEW

**Comment by schrodingersket** [comment]
Whoops! I didn't actually mean to commit that line. I'll fix and re-push. Thanks!

**Comment by schrodingersket** [comment]
@fairecasoimeme - I've updated the pull request. Let me know if this is what you had in mind.

**Comment by pipiche38** [comment]
For reference, could you explain what is exactly not working ? What is the new behaviour bringing ? What is the downward compatibility ?

**Comment by schrodingersket** [comment]
@pipiche38 - sure! My particular use-case is that I found that reading the Instantaneous Demand attribute from the power metering cluster (`0x0702`) was returning zero. After digging into the code, it seems that any values over `uint16` seem to be returning erroneous data. In particular, the value I was trying to read was a `uint48`.

This fix causes the correct value to be returned (as confirmed by a Kill-a-Watt I'd hooked up to verify the accuracy of the reading); the original code was intended to walk through an area of memory 8 bits at a time in order to stuff the bytes into a larger variable in the correct order; due to the missing pointer increment, the same area of memory was being repeatedly read instead.

This fix is fully backward-compatible with existing builds, and will not require any PDM changes, as it's related to reading incoming data from other devices.

**Comment by pipiche38** [comment]
But I’m reading uint48 on cluster 0x0702/0x0400 without any problem 

Envoyé de mon iPhone

**Comment by schrodingersket** [comment]
Are you getting any data past the first byte? Because I get that value back, but none beyond that.

**Comment by pipiche38** [comment]
What I can tell is that I’m getting the right measure, and didn’t have a look in details.

I’m getting Instant power consumption from a Salus smart plug

**Comment by schrodingersket** [comment]
Hmm... okay. I'm testing against this and not getting the correct reading without the fix: https://www.telkonet.com/platform/hardware/ecoguard/

Are you receiving valid data on a `report individual attribute response` message (msg type `0x8102`)? That's what I'm failing to receive valid data on without this fix.

**Comment by pipiche38** [comment]
What type of code are you using to interact with Zigate ? Don't you have an issue of alignment?
I did check my code and in fact 0x0702/0x0400 is returning a Data Type of 0x2a and no 0x25

So it is a Uint24 and is not aligned, so it might be your issue !

Here after is the trick I'm using in python3 to convert the uint24 into a python int
`str(struct.unpack('i',struct.pack('I',int("0"+Attribute,16)))[0])`

**Comment by ISO-B** [comment]
For me this looks good and as @schrodingersket fixed thing that @fairecasoimeme  mentioned this should be ready for merge.

**Comment by pipiche38** [comment]
@ISO-B , @fairecasoimeme  would it be possible when a PR is merged to have a build done , so we get access to the revised firmware version for test purposes ?

**Comment by ISO-B** [comment]
Sure. I can actually build it tomorrow even if it is not merged.

**Comment by ISO-B** [comment]
I made build with all currently open pull requests included: https://github.com/ISO-B/ZiGate-firmware/releases/tag/ZiGate_dev

**Comment by fairecasoimeme** [comment]
Sorry for delay but it's ok for me too.

**Comment by pipiche38** [comment]
I did test with https://github.com/ISO-B/ZiGate-firmware/releases/tag/ZiGate_dev and do not see any improvement on Data Type 0x25. Will check with sniffer during the week-end, but still the 4 first bytes are set to 0x0000 while the 4 last are correct. So no improvement!

**Comment by fairecasoimeme** [comment]
I'll try to test this datatype too.  let's see

**Comment by pipiche38** [comment]
> 
> 
> I made build with all currently open pull requests included: https://github.com/ISO-B/ZiGate-firmware/releases/tag/ZiGate_dev

Is that expected to have 031a (instead of 031b) in this beta firmware ?

**Comment by ISO-B** [comment]
Yes, because I forgot to change values :)

**Comment by pipiche38** [comment]
Ok, no issue then. 
However shouldn't we put in place a special numbering for 'beta' type of firmware in order to avoid mixing release and pre-release. ?

**Pull request merged**
