### PR TITLE
Added support for Ikea remote left right buttons.

### PR DESCRIPTION
**Pull request by ISO-B**
ZiGate can now handle Ikea Trådfri 5 button remote left and right buttons scene command forwarding for user. Also removed exra ^M line-endings from files that I edited. Part of #64

### CODE REVIEW

**Comment by pipiche38** [comment]
This sound awesome. Is there anything to do on the layer above ?

**Comment by ISO-B** [comment]
Now it is possible to get info from button click, down and up events if you add ZiGate to same group with remote. This doesn't do anything with Scenes cluster like regular scenes commands.

**Comment by fairecasoimeme** [comment]
I'll test this week. Thanks for all !

**Comment by fairecasoimeme** [comment]
works great ! thanks !

**Pull request merged**
