### PR TITLE
Add Raw Mode, command 0x0002

### PR DESCRIPTION
**Pull request by doudz**
Add command 0x0002 to enable "Raw mode"
Raw mode will generate response 0x8002 instead of standard endpoint response and general APS event

The command 0x0002 accept one parameter 0x00 to disable raw mode, 0x01 to enable raw mode

### CODE REVIEW

**Comment by ISO-B** [comment]
Didn't test it put it looks good. Would you mind to changes tabs to spaces so indentation would look correct?

**Comment by ISO-B** [comment]
Should raw mode stay enabled after power off? If so sZllState might be good and correct place to store its state.

**Comment by doudz** [comment]
How use sZllState ? (Sorry but I don't know C ...)

**Comment by ISO-B** [comment]
- app_common.h has typedef for tsZllState struct, add bool bRawMode at end of struct
- Initialize it to 0 in app_start.c where sZllState is initialized
- Now you can access it by using sZllState.bRawMode
- Replace your boolean variable bRawMode with sZllState.bRawMode

**Comment by doudz** [comment]
Oh it sounds easy.
Thank you

**Comment by ISO-B** [comment]
I can make corrections to EEPROM sizes for migrations after this PR is merged.

**Comment by ISO-B** [comment]
Correct me if I am wrong but #178 is related to this. This is going to fix #133?

**Comment by doudz** [comment]
#178 is just a doc error, I found it using the raw mode
and yes it fix #133 and now it's possible to support zigpy #129 
it's also related to #153 ;)

**Comment by pipiche38** [comment]
> Should raw mode stay enabled after power off? If so sZllState might be good and correct place to store its state.

Then we need to make sure that a Software Reset is also resetting 0x0011 Raw Mode, which shouldn't be a default mode.

**Comment by doudz** [comment]
Why ? If someone uses raw mode and wants to reset zigate but still use raw mode

**Comment by pipiche38** [comment]
Reset should bring to default mode. And from my end we can agree that default mode is what we have today before the new raw mode introduction.



Envoyé de mon iPhone

**Comment by ISO-B** [comment]
Erasing pdm will reset mode, but I need to check what software reset does.

**Comment by ISO-B** [comment]
ZiGate documentation is bit unclear on commands reset (0x0011) and Erase Persistent Data (0x0012). Reset will restart ZiGate without saving anything before and it should reset RAM data. Erase PD will erase data PDM data and perform reset after that. Based on this reset should not change Raw Mode state, because it won't change anything else either.

I suggest renaming 0x0011 to Restart and 0x0012 to Reset to Factory New (or something like that).

**Comment by pipiche38** [comment]
Fine but then we need a command to disable raw mode
And an other one to get status if we are in raw mode or not

**Comment by ISO-B** [comment]
> 
> The command 0x0002 accept one parameter 0x00 to disable raw mode, 0x01 to enable raw mode

I don't see use for command that would return raw mode state since it's quite intuitive. When raw mode is enabled you get 0x8002 responses otherwise it is disabled.

**Comment by doudz** [comment]
I agree, there's no need for a command to get the state.
There's no case when you just want to know the state.

If you want raw mode, you don't need to ask for state and if wrong state, enable raw mode, instead just enable raw mode.

And if you don't want raw mode , just disable raw mode

Raw mode is not the default mode, it's a special mode that need to be enabled

**Comment by pipiche38** [comment]
This is were I’m concerned if the software reset is now rename in reboot and do not put the ZiGate in it’s default mode we could be in the case were raw mode is enabled.

Last I think it is a best practice when you enable/disable to have a status function.


Envoyé de mon iPhone

**Comment by ISO-B** [comment]
If we would change that reset(which is just software reboot) changes raw mode state it would be very illogical since it won't reset any other saved values. 

Yes I agree with you that it is the best practice to have status function when you can set something, but I see this case is exception to "rule".  In my opinion main use case for raw mode is Zigpy, which I assume needs different library than normal usage of ZiGate. Because you need different mode for each library you can just set raw mode state. For me it seems unnecessarily to first ask state and then change if needed. Compared to that just setting state which I want it to be. When making Zigpy compatible library just set raw mode enabled at startup. If your library is just using ZiGate normally you can set raw mode to disable at startup if you wan't to be sure that it is disabled.

**Comment by pipiche38** [comment]
Fine with me. If the strategy is to develop a firmware which perform only for a plugin/library. I'm ok
I'm not the owner of the firmware and will follow

**Comment by doudz** [comment]
@pipiche38 imagine we add a get a command, what you do in your plugin ?
- get raw state
- wait for reply
- if needed disable raw state

So in better case you send one command and treat a reply, in worst you send another command to disable raw state, so two commands

Or you can just disable raw in any case , you send one command and that's all

**Comment by doudz** [comment]
And again, raw mode is not the default , so you will not enter in raw in normal operation

**Comment by fairecasoimeme** [comment]
Hi all,
Sorry because i don't have a lot of time, but I will test this weekend and I will rule on this issue.

Thanks

**Comment by fairecasoimeme** [comment]
Ok, I tested raw mode with a door sensor. I got 2 packets instead of 1. 
14:58:58.011 <- 01 80 02 00 15 92 00 01 04 00 06 01 01 02 13 EF 02 00 00 18 30 0A 00 00 10 01 C9 03
14:58:59.089 <- 01 80 02 00 15 92 00 01 04 00 06 01 01 02 13 EF 02 00 00 18 30 0A 00 00 10 01 C9 03

I agree on the following : 
* When reset, switch to normal mode --> tested OK
* RAW mode must be activated by command --> tested OK

**Comment by doudz** [comment]
I noticed the same, same packet is sent 2 or 3 times but it's not a problem. I suppose this is because the sensor really send the packet many times. Or maybe there some ack missing ?

**Comment by doudz** [comment]
Did you check that raw is preserved after power down ?

**Comment by fairecasoimeme** [comment]
> 
> 
> I noticed the same, same packet is sent 2 or 3 times but it's not a problem. I suppose this is because the sensor really send the packet many times. Or maybe there some ack missing ?

I verified with the sniffer and there is 1 single frame.

**Comment by fairecasoimeme** [comment]
> 
> 
> Did you check that raw mode is preserved after power down ?

Oups, it's a mistake  : 
In fact, in normal mode, when you reset, you switch to raw mode. I think it's not a good solution.

First solution : save context in memory and you can switch in raw mode or normal mode even if power down or reset

Second solution: normal mode is the default mode and if you do the raw mode command when reset or power down, ZiGate must switch to normal mode

**Comment by doudz** [comment]
normal mode should be the default for sure,
but raw mode should be preserved after power down, just because of ZiGate Wifi.
ZiGate Wifi could be power down/up independently so in that case the remote program just doesn't see this "reset"

**Comment by fairecasoimeme** [comment]
Ok, it's weird. I re-tested and the solution 2 seems to be ok now. However, I was sure the raw mode was the default. I'll do other test to be sure yet

**Comment by doudz** [comment]
I thing the good things could be :
- Fresh zigate = normal mode
- enabling raw mode = keep raw mode, even after reset or power down 
- Power down = restore raw mode (hard reboot)
- Reset = restore raw mode (since it's a soft reboot)
- Factory reset = return to normal mode

**Comment by fairecasoimeme** [comment]
ok but it's not quite easy. I don't know how to save (smartly) the mode because It could do a lot of write and It's not really good. There is the retention of RAM solution (when reset only) but It's heavy to handle.
I think the best compromise is the solution 2 with a sending to raw mode in the loading of zigpy plugin.

What do you think ? @ISO-B what do you think too ?

**Comment by doudz** [comment]
saving as been added by using sZllState.bRawMode

**Comment by perdro6996** [comment]
0x0011 is expected to be a Reset command , and in such should make the zigate returning to its default state.

This is like that since Zigate is live, and changing this behaviour will create a break in the compatibility, which I saw have been always protected in the past .

Screenshot 2019-03-27 at 22 27 46

**Comment by ISO-B** [comment]
> 
> 
> ok but it's not quite easy. I don't know how to save (smartly) the mode because It could do a lot of write and It's not really good. There is the retention of RAM solution (when reset only) but It's heavy to handle.
> I think the best compromise is the solution 2 with a sending to raw mode in the loading of zigpy plugin.
> 
> What do you think ? @ISO-B what do you think too ?

Adding RawMode state to sZllState(keeps track of other ZiGate states) should work fine. It is not that big change, it only needs minor changes to pdm migration part. I can do these changes today.

------------------------------
Command 0x0011 is documented as reset, but what it does it will only restart ZiGate it won't change any saved things. It calls vAHI_SwReset() function, which is described in JN-UG-3087 v1.5(page 182) 
>
>This function generates an internal reset which completely re-starts the system
through the full reset sequence.
>
>Caution: This reset has the same effect as pulling the
external RESETN line low and is likely to result in the loss of
the contents of on-chip RAM.

So as you can see it will only reset stuff on RAM which is same what power loss would do.

There is two logical ways to correct this:
1. Change 0x0011 to work as reset and make it reset RawMode and OTA variables from sZllState. You may wonder why reset OTA variables too. It is because OTA information is in RAM but some parameters are saved to sZllState. Introduce new command restart which would do what 0x0011 has been doing until now.
2. Change 0x0011 name in documentation to restart and use 0x0012 as reset since it will reset ZiGate to be factory new.

I would recommend option 2. First of all, there should be no reason why ZiGate would enter to raw mode without you knowing or commanding it. If this happens why would you like to also reset OTA variables too to get out of raw mode. We could make reset only to reset raw mode right? Yes we could, but you can also do this by sending 0x0002 with parameter 0 and there is no need for restart. 

In my opinion there is no need for reset command, because if you want reset you most likely want to reset everything and then you can use 0x0012. I don't know if there is any real world usage where you would like to change raw mode within your program/library in runtime. Just set raw mode which ever mode you need at start up and don't touch it after that.

**Comment by ISO-B** [comment]
Tested migration and adding bool RawMode to tsZllState won't even change tsZllState change. This means that there is no need to do changes to migration part.

**Comment by fairecasoimeme** [comment]
Ok, that's good for me. Thx for job

**Pull request merged**
