### PR TITLE
284: Added support for Develco Air Quality Sensor (Develco AQSZB-110)

### PR DESCRIPTION
**Pull request by schrodingersket**
Tested with device referenced in title. Happy to add a separate endpoint for Develco products, but I'm not quite sure what the best way to do that is. Pointers would be appreciated (:

Addresses issue #284

### CODE REVIEW

**Comment by fairecasoimeme** [comment]
Hi,
I think your PR could explode the memory RAM.
We have to rethink the way to add new feature with keeping the compatibility of number of devices

Fred

**Comment by schrodingersket** [comment]
Could you elaborate a bit more as to what the problem is? The only thing I can think of off the top of my head is that an additional data type is being added to the HA profile whenever and endpoint is registered that utilizes HA (Which should only be `0x01`... I'd expect any other endpoints to only implement cluster necessary for the behavior of that device). I've been running this on my chip for about four days so far and haven't seen any issues - do you have a set of steps I could follow to reproduce the "blowing up" behavior?

**Comment by schrodingersket** [comment]
HAH whoops. It looks like there were some generated files that got added that shouldn't be in there. My bad; removing those now.

**Comment by schrodingersket** [comment]
@fairecasoimeme - good catch on the generated files. Those have been removed, and I added a `.gitignore` file to exclude those from future commits. PR 284 should now only be clusters for the VOC sensor referenced in the title.

**Comment by schrodingersket** [comment]
Closing in favor of #313 .

**Comment by pipiche38** [comment]
What is the Cluster Id used for the Quality Air sensor ?

**Comment by schrodingersket** [comment]
@pipiche38 `0xfc03` for the Develco VOC sensor.

**Pull request closed without merging**
