### PR TITLE
Fixed 0x8030 and 0x8031 responses

### PR DESCRIPTION
**Pull request by ISO-B**
Switched both responses to get data from correct place. Also removed
clusterId as it was internal cluster id and has nothing to do bind
commands cluster. #122

### CODE REVIEW

**Comment by pipiche38** [comment]
I have used https://github.com/ISO-B/ZiGate-firmware/releases/tag/ZiGate_dev, and iit looks like the data provided now in 0x8030 are not at all in the same format as before.

Expected DataStructure is:
```
Sequence Number uint8
Status uint8
SourceEp uint8
Source Addr Mode uint8
Source Add uint16/uint64
```
Here after are some examples of Payload I received
```
2d0038005d0000
2e0038005d0000
2f0038005d0000
300038005d0000
```

While I can find Sequence number and Status,  the next bytes looks a mystery

**Comment by pipiche38** [comment]
Don't know why it doesn't work, but while looking after your change, I think that you break backward compatibility by adding the Destination Ep which was not present before

**Comment by ISO-B** [comment]
Yes, noticed that I breaked it, but it was intentionally. There was no way to avoid it since last version has cluster id as last parameter. I can move SrcEp to end of message. Dst should point to remote node. 
```
Sequence uint8
Status uint8
SrcEp uint8
DstEp uint8
DstAddressMode uint8
DstAddress uint16 or uint64 depending DstAddressMode
```

**Comment by pipiche38** [comment]
But ClusterId was never working. So bringing to the end of the message ( after the Source Address) would makes more  sense.

Despite that, the data I'm getting are not correct, so there is an other issue.

**Comment by pipiche38** [comment]
Might have a clue for the Short Address which is unknown.  This in fact seems to related to an old Short Address.

**Comment by ISO-B** [comment]
Thanks @pipiche38  for doing testing. Now I managed to finally find why message doesn't make sense. Struct that we are using to getting data is correct one, but we are doing it on wrong time. I didn't check event orders but I assume that first happens ZPS_EVENT_APS_DATA_INDICATION in which we are currently sending 8030 and 8031 responses. After that happens ZPS_EVENT_ZDO_BIND/ZPS_EVENT_ZDO_UNBIND which has data about bind node. I will need to check order and probably add new response codes for responses with EP data. Those later events are only triggered if bind was successfully done

**Comment by pipiche38** [comment]
Sound good, receiving the confirmation of a correct Bind/Unbind is good.

**Comment by pipiche38** [comment]
That one should be closed and not implemented. We are using SQN

**Pull request closed without merging**
