### PR TITLE
Fixes to group commands and SDK tools

### PR DESCRIPTION
**Pull request by ISO-B**
Library files were ok, but SDK files were still broken. Replaced tools folder content with working versions. https://github.com/fairecasoimeme/ZiGate/issues/105#issuecomment-458942801

Fixed group commands to send correct responses. Reported by @KiwiHC16 https://github.com/fairecasoimeme/ZiGate/issues/64#issuecomment-457641540

After fixing group commands, group 0x0000 couldn't be anymore added. Had to modify group manager to accept that group. Ikea Trådfri control outlet remote controller uses this group to sending commands for other devices. https://github.com/fairecasoimeme/ZiGate/issues/64#issuecomment-459354195

### CODE REVIEW

**Comment by pipiche38** [comment]
Did you check the impact on Xiaomi Smat plug which are member of group 0x0000 by default after a reset ?

**Comment by fairecasoimeme** [comment]
It seems to be good on my side

**Comment by KiwiHC16** [comment]
WOrk well and included in the plugin.

**Comment by pipiche38** [comment]
latest version including the PR seems very good. 

addGroup and getGroupMembership works well.

No issue with Xiaomi Smartplu which belongs by default to Group 0x0000
   - have been able to remove from group 0x0000
   - have been able to add back to group 0x0000

Good job

**Pull request merged**
